In [29]:
T = 20
t = 10

import numpy as np

V = np.copy(np.random.random(T-t+1) * 10)

C = 1 + (1 - np.e**(-T+t-1)) / (1 - 1 / np.e)

i = np.arange(t, T+1)

fun = lambda x: -np.sum((V-T+i-np.log(C*x/(1-np.sum(x))))*x)

bnds = [(0, None) for i in range(T-t+1)]

cons = {'type': 'ineq', 'fun': lambda x:  1-np.sum(x)}

x1_0 = np.zeros(T-t+1) + 1e-3


from scipy.optimize import minimize

res = minimize(fun, x1_0, method='SLSQP', bounds=bnds,
               constraints=cons, options={'disp': True})

Optimization terminated successfully.    (Exit mode 0)
            Current function value: -4.491318808511785
            Iterations: 15
            Function evaluations: 222
            Gradient evaluations: 15


d:\program files\python36\lib\site-packages\ipykernel_launcher.py:12: RuntimeWarning: divide by zero encountered in log
  if sys.path[0] == '':
d:\program files\python36\lib\site-packages\ipykernel_launcher.py:12: RuntimeWarning: invalid value encountered in log
  if sys.path[0] == '':
d:\program files\python36\lib\site-packages\ipykernel_launcher.py:12: RuntimeWarning: invalid value encountered in multiply
  if sys.path[0] == '':


In [30]:
x1 = res.x
x1

array([5.49436328e-14, 8.37551845e-07, 6.27641795e-14, 6.41598191e-07,
       2.08325332e-07, 2.42100672e-02, 4.30812992e-02, 2.02897095e-01,
       3.43303307e-01, 8.20676303e-04, 2.57590681e-01])

In [31]:
np.sum(x1)

0.8719048140997037

In [32]:
-fun(x1)

4.491318808511785

In [33]:
p = V-T+i-np.log(C*x1/(1-np.sum(x1)))
p

array([20.771334  ,  4.76821866, 19.66267676,  4.94700868, 10.27374537,
        5.20068779,  1.22184089,  5.03107426,  5.64252951,  4.67282326,
        5.24490143])

上述是以x1为优化对象，现在我们以p为优化对象，看看两者是否一样

In [42]:
def fun_2(x):
    
    temp = np.exp(V-x-T+i)
    
    return -np.sum(x*temp/(C+np.sum(temp)))

p_0 = np.zeros(T-t+1) + 1e-3

from scipy.optimize import minimize

res = minimize(fun_2, p_0, method='SLSQP', options={'disp': True})

Optimization terminated successfully.    (Exit mode 0)
            Current function value: -4.705662674727992
            Iterations: 43
            Function evaluations: 569
            Gradient evaluations: 43


In [43]:
p = res.x
p

array([0.3431138 , 0.55731938, 0.13675178, 0.5155342 , 5.82558742,
       5.70166246, 5.56879594, 5.70674802, 5.70507001, 6.39014193,
       5.70592235])

In [44]:
x1 = np.exp(V-p-T+i) / (C + np.sum(np.exp(V-p-T+i)))
x1

array([5.58944988e-05, 7.71561256e-05, 2.59001165e-05, 7.36913364e-05,
       2.43299337e-05, 2.00453596e-02, 7.62111627e-04, 1.41066156e-01,
       4.40661781e-01, 2.01343799e-04, 2.21972768e-01])

In [45]:
-fun(x1)

4.705662674727994

In [46]:
-fun_2(p)

4.705662674727992

我个人认为没有转化错，因为x1最优解的值太小了，所以优化x1结果更不稳定，优化p结果更稳定

In [49]:
T = 5

In [51]:
V = np.triu(np.copy(np.random.random(T ** 2) * 10).reshape(T, T))
V

array([[5.05829955, 4.38218733, 3.95086789, 8.04758078, 4.75297128],
       [0.        , 7.6913108 , 9.5103961 , 3.13728536, 8.10029128],
       [0.        , 0.        , 2.28904127, 0.92488434, 7.36856463],
       [0.        , 0.        , 0.        , 1.97394028, 7.85841857],
       [0.        , 0.        , 0.        , 0.        , 6.91009141]])

In [53]:
C = np.array([1 + (1 - np.e**(-T+t-1)) / (1 - 1 / np.e) for t in range(1, T+1)])
C

array([2.57131743, 2.55300179, 2.50321472, 2.36787944, 2.        ])

In [59]:
i = np.triu(np.tile(np.arange(1, T+1), (5, 1)))
i

array([[1, 2, 3, 4, 5],
       [0, 2, 3, 4, 5],
       [0, 0, 3, 4, 5],
       [0, 0, 0, 4, 5],
       [0, 0, 0, 0, 5]])

In [64]:
a = np.copy(np.random.random(T) * 10)
a

array([8.9531971 , 4.19334349, 9.47635593, 7.63831688, 7.78118251])

In [70]:
def fun_3(x):
    
    out = 0
    
    for j in range(T):
        
        temp_V = V[j, j:]
        temp_i = i[j, j:]
        
        temp_x = x[j:]
        
        temp_a = a[j]
        temp_C = C[j]
        
        temp_temp = np.exp(temp_V-temp_x-T+temp_i)
        out += temp_a * np.sum(temp_x*temp_temp/(temp_C+np.sum(temp_temp)))
    
    return -out

In [71]:
p_0 = np.zeros(T) + 1e-3

from scipy.optimize import minimize

res = minimize(fun_3, p_0, method='SLSQP', options={'disp': True})

Optimization terminated successfully.    (Exit mode 0)
            Current function value: -156.88531382918464
            Iterations: 27
            Function evaluations: 199
            Gradient evaluations: 27


d:\program files\python36\lib\site-packages\ipykernel_launcher.py:15: RuntimeWarning: overflow encountered in exp
  from ipykernel import kernelapp as app
d:\program files\python36\lib\site-packages\ipykernel_launcher.py:16: RuntimeWarning: invalid value encountered in true_divide
  app.launch_new_instance()


In [72]:
p = res.x
p

array([4.8559605 , 5.69150139, 5.81338369, 4.85709256, 5.20128414])

In [74]:
for j in range(T):
    
    print(np.exp(V[j, j:]-p[j:]-T+i[j, j:]) / (C[j] + np.sum(np.exp(V[j, j:]-p[j:]-T+i[j, j:]))))

[0.00183699 0.00110128 0.00172163 0.7323632  0.05232506]
[0.0138272  0.20517031 0.00247693 0.68254958]
[3.54566786e-04 6.41000948e-04 7.76474935e-01]
[0.00123684 0.85649559]
[0.73412638]


进一步的，我们再加一个k

In [81]:
T = 5
K = 5

In [82]:
V = np.triu(np.copy(np.random.random(T ** 2 * k) * 10).reshape(K, T, T))
V

array([[[9.91465912, 2.253602  , 4.09987104, 2.36682657, 5.6531446 ],
        [0.        , 5.85212574, 7.39122661, 6.62285866, 9.85764868],
        [0.        , 0.        , 1.37844526, 2.03594798, 3.87460196],
        [0.        , 0.        , 0.        , 7.87224325, 0.29176928],
        [0.        , 0.        , 0.        , 0.        , 1.51883682]],

       [[5.10832329, 4.33178859, 8.50398837, 7.24708992, 8.08024348],
        [0.        , 8.93278069, 2.7987843 , 7.51710529, 9.55779675],
        [0.        , 0.        , 5.29716385, 4.43977738, 0.94351115],
        [0.        , 0.        , 0.        , 9.25868274, 2.13014322],
        [0.        , 0.        , 0.        , 0.        , 1.19521969]],

       [[5.50495393, 3.5149056 , 9.77612476, 7.9741235 , 7.42454574],
        [0.        , 8.66135925, 1.05261789, 3.63259055, 3.49123614],
        [0.        , 0.        , 6.90850733, 9.3666354 , 8.07419442],
        [0.        , 0.        , 0.        , 9.73032822, 9.9181832 ],
        [0.     

In [77]:
C = np.array([1 + (1 - np.e**(-T+t-1)) / (1 - 1 / np.e) for t in range(1, T+1)])
C

array([2.57131743, 2.55300179, 2.50321472, 2.36787944, 2.        ])

In [78]:
i = np.triu(np.tile(np.arange(1, T+1), (5, 1)))
i

array([[1, 2, 3, 4, 5],
       [0, 2, 3, 4, 5],
       [0, 0, 3, 4, 5],
       [0, 0, 0, 4, 5],
       [0, 0, 0, 0, 5]])

In [84]:
a = np.copy(np.random.random(T * K) * 10).reshape(K, T)
a

array([[7.92792213, 2.7229757 , 1.33188009, 7.57199219, 0.52701871],
       [0.78885791, 1.29891858, 4.85731315, 8.63245254, 1.52867507],
       [7.16350555, 6.81156256, 5.47352022, 7.03213401, 4.39259424],
       [1.88816135, 7.44918726, 5.25623055, 1.79465849, 1.90270275],
       [0.38394826, 7.68262652, 5.23782811, 5.60729796, 0.9436954 ]])

In [85]:
def fun_4(x):
    
    out = 0
    
    for k in range(K):
    
        for j in range(T):

            temp_V = V[k, j, j:]
            temp_i = i[j, j:]

            temp_x = x[j:]

            temp_a = a[k, j]
            temp_C = C[j]

            temp_temp = np.exp(temp_V-temp_x-T+temp_i)
            out += temp_a * np.sum(temp_x*temp_temp/(temp_C+np.sum(temp_temp)))
    
    return -out

In [89]:
p_0 = np.zeros(T) + 1e-3

from scipy.optimize import minimize

res = minimize(fun_4, p_0, method='SLSQP', options={'disp': True})

Optimization terminated successfully.    (Exit mode 0)
            Current function value: -382.43282065044207
            Iterations: 24
            Function evaluations: 189
            Gradient evaluations: 24


d:\program files\python36\lib\site-packages\ipykernel_launcher.py:17: RuntimeWarning: overflow encountered in exp
d:\program files\python36\lib\site-packages\ipykernel_launcher.py:18: RuntimeWarning: invalid value encountered in true_divide


In [90]:
p1 = res.x
p1

array([4.01213229, 4.14050384, 4.57127379, 5.61381911, 6.30784688])